server:
  port: $SERVER_PORT  # 포트

  servlet:
    context-path: /v3  # 서버 url 뒤에 추가되는 path
    session:
      tracking-modes: cookie  # url jsession 제거 (서버측에선 클라이언트가 쿠키를 사용하는지 알 수 없으므로 url 뒤 jsession 을 붙히게 됨)
    encoding:
      force-response: true  # 응답 강제 인코딩
      force-request: true

  # Response Body 압축 (gzip)
  # 주의: 기본 타입 목록(server.compression.mime-types)에 service/json 없음.
  compression:
    enabled: true
    min-response-size: 2048 # 압축 수행할 최소 Content-Length 값
---
spring:
  # Profile
  config:
    activate:
      on-profile: prod

  # JPA
  jpa:
    # show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
      # show_sql: true
      # use_sql_comments: true
      # format_sql: true
      # generate_statistics: true

    hibernate:
      ddl-auto: update  # 서버 구동시 ddl 전략

  # DATASOURCE
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://$DB_IP:3306/$DB_NAME?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false&validationQuery=select 1&serverTimezone=Asia/Seoul
      username: $DB_USERNAME
      password: $DB_PASSWORD
      connection-init-sql: "SET NAMES 'utf8mb4'"  # 이모지 사용

  # DATA REST
  # (test 용, 실제로 사용하지 않음)
  data:
    rest:
      base-path: /jpa
      detection-strategy: default

  servlet:
    # multipart 파일 전송
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  # RabbitMQ
  rabbitmq:
    host: $RABBITMQ_IP
    port: $RABBITMQ_PORT
    username: $RABBITMQ_USERNAME
    password: $RABBITMQ_PASSWORD

---
# SLF4J
logging:
  file:
    path: log/slf4j.log
  level:
    org:
      hibernate:
        # SQL: debug     # sql 로깅
        type:
          descriptor:
          # sql: trace   # sql 로깅
---
# ACTUATOR
management:
  health:
    diskspace:
      enabled: false
    status:
      order: DOWN, MAINTENANCE, UNKNOWN, UP
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
        exclude: env, beans
---
file:
  # 프로젝트 안 upload-dir: ./uploads
  # 맥 upload-dir: /Users/nakzzi/Downloads/assets
  upload-dir: ./uploads # file upload url
---
static:
  resource:
    # 맥 location: /Users/nakzzi/Downloads/assets/ -> 확인필요.
    location: ./assets/  # file download url
---
